version: "0.2"
ignorePaths:
  - .gitignore
  - .editorconfig
  - convert-utf8bom-to-utf8.bat
  - convert-utf8bom-to-utf8.ps1
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords: []
import: []
